package controllers_gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class UserPortalOfCEOController {
	@FXML
	private Button btnViewQuarterlyReports;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Button btnViewMonthlyReports;
	@FXML
	private Button btnHelp;

	// Event Listener on Button[#btnViewQuarterlyReports].onAction
	@FXML
	public void getQuarterlyReports(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnViewMonthlyReports].onAction
	@FXML
	public void getMonthlyReports(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
}
