package controllers_gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class UserPortalOfBranchManagerController {
	@FXML
	private Button btnViewSysReports;
	@FXML
	private Button btnCompanyRegManagement;
	@FXML
	private Button btnEditCustomerInfo;
	@FXML
	private Button btnSupplierReg;
	@FXML
	private Button btnCustomerReg;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Button btnAddQuarterlyReports;
	@FXML
	private Label customerNameLabel;
	@FXML
	private Button btnHelp;

	// Event Listener on Button[#btnViewSysReports].onAction
	@FXML
	public void getViewReports(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCompanyRegManagement].onAction
	@FXML
	public void getCompRegManagement(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditCustomerInfo].onAction
	@FXML
	public void getEditCustomerInfo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupplierReg].onAction
	@FXML
	public void getSupplierReg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCustomerReg].onAction
	@FXML
	public void getCustomerReg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAddQuarterlyReports].onAction
	@FXML
	public void getAddQuarterlyReports(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
}
