package controllers_gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class UserPortalOfHRManagerController {
	@FXML
	private Button btnStartOrder;
	@FXML
	private Button btnCompanyReg;
	@FXML
	private Button btnBusinessCustomerConfirm;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Button btnHelp;
	@FXML
	private Label customerNameLabel;
	@FXML
	private Label companyNameLabel;
	@FXML
	private ComboBox homeBranchCombo;

	// Event Listener on Button[#btnStartOrder].onAction
	@FXML
	public void getStartOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCompanyReg].onAction
	@FXML
	public void getCompanyReg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBusinessCustomerConfirm].onAction
	@FXML
	public void getBusinessCustomerConfirm(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#homeBranchCombo].onAction
	@FXML
	public void getHomeBranch(ActionEvent event) {
		// TODO Autogenerated
	}
}
