package controllers_gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import bitemeclient.PopUpMessages;
import communication.Answer;
import communication.Message;
import communication.Task;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;
import users.Branch;
import users.BusinessCustomer;
import users.ConfirmationStatus;
import users.HrManager;
import users.User;
import javafx.scene.control.ComboBox;

/**
 * 
 * @author Mousa, Srour
 * @author Alexander, Martinov
 * Class description: 
 * This is a class for 
 * controlling the UI of hrManager
 * form.
 * 
 * @version 09/12/2021
 */
public class UserPortalOfBusinessCustomerController extends AbstractBiteMeController implements Initializable{
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Label customerNameLabel;
	@FXML
	private Button btnHelp;
	@FXML
	private Button btnStartOrder;

    @FXML
    private Button viewOrdersBtn;
	@FXML
	private Label companyNameLabel;
	
    @FXML
    private Text companyName;
    @FXML
    private Text businessCustomerName;
    @FXML
    private Text statusText;
    
	public static FXMLLoader loader;
	private static UserPortalOfBusinessCustomerController userPortalOfBusinessCustomerController;
	
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
		Message message= new Message(Task.LOGOUT,Answer.WAIT_RESPONSE,connectedUser);
		sendToClient(message);
		connectedUser=null;
		Message disconnectMessage= new Message(Task.CLIENT_DICONNECT,Answer.WAIT_RESPONSE,null);
		sendToClient(disconnectMessage);
		System.exit(0);
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		Message message= new Message(Task.LOGOUT,Answer.WAIT_RESPONSE,connectedUser);
		sendToClient(message);
		connectedUser=null;
		setToLoginScreen(event);
	}
	
	/**
	 * This is pop message for the help button.
	 * @param event
	 */
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		PopUpMessages.helpMessage("This is the Main screen of the Business Customer, Please press any button!");	

	}
	
	/**
	 * When preset start order button,
	 * the screen will change to the first screen in the 
	 * order process which is the W4C identification.
	 * 
	 * @param event
	 */
	// Event Listener on Button[#btnStartOrder].onAction
	@FXML
	public void getStartOrder(ActionEvent event) {
		((Node) event.getSource()).getScene().getWindow().hide(); // hiding primary window
		OrderW4cIdentificationScreenController w4cIdentificationController = new OrderW4cIdentificationScreenController();
		w4cIdentificationController.initW4cIdentificationScreen(); // call the init of the next screen
	}
	/**
	 * 
	 * @param event
	 */
    @FXML
    void getViewOrdersBtn(ActionEvent event) {
     	((Node) event.getSource()).getScene().getWindow().hide(); // hiding primary window
    	WatchOrderHistoryScreenController watchOrderHistoryScreenController = new WatchOrderHistoryScreenController();
    	watchOrderHistoryScreenController.initOrderHistoryScreen(); // call the init of the next screen
    }
	
	
	/**
	 * Returns to login screen
	 * @param event
	 */
	private void setToLoginScreen(ActionEvent event) {
		Platform.runLater(new Runnable() {
			@Override
			public void run() {
				FXMLLoader loader = new FXMLLoader();
				Pane root;
				try {
					Stage Stage = new Stage();
					Stage.setResizable(false);
					root = loader.load(getClass().getResource("/fxmls/LoginScreen.fxml").openStream());
					LoginScreenController LSC = loader.getController();
					LSC.initLoginScreen();
					Stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
						@Override
						public void handle(WindowEvent event) { 
							event.consume();
							Stage.close();
						}
					});
				} catch (IOException e) {
					e.printStackTrace();
				}
				((Node) event.getSource()).getScene().getWindow().hide();
			}
		});
	}
	
	/**
	 * This is the initialization function for this 
	 * screen.
	 * 
	 * @param primaryStage
	 * @param fxmlPath
	 */
	public void initBusinessCustomerUserPortal(Stage primaryStage,String fxmlPath) {
		Platform.runLater(new Runnable() {
			@Override
			public void run() {
				loader = new FXMLLoader();
				Pane root;
				try {
					primaryStage.hide(); 
					Stage Stage = new Stage();
					Stage.setResizable(false);
					root = loader.load(getClass().getResource(fxmlPath).openStream());
					userPortalOfBusinessCustomerController = loader.getController();
					Scene scene = new Scene(root);
					Stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
						@Override
						public void handle(WindowEvent event) { 
							event.consume();
							Stage.close();
						}
					});
					scene.getStylesheets().add(getClass().getResource("/css/G3_BiteMe_Main_Style_Sheet.css").toExternalForm());
					Stage.setTitle("Business Customer Main Screen");
					Stage.setScene(scene);
					Stage.show();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});
	}
	
	/**
	 * Init customer portal again.
	 */
	public void initPortalAgain() {
		loader = new FXMLLoader();
		Stage primaryStage = new Stage();
		Pane root = null;
		try {
			root = loader.load(getClass().getResource("/fxmls/UserPortalOfBusinessCustomer.fxml").openStream());
			userPortalOfBusinessCustomerController = loader.getController();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Scene scene = new Scene(root);
		scene.getStylesheets().add(getClass().getResource("/css/G3_BiteMe_Main_Style_Sheet.css").toExternalForm());
		primaryStage.setScene(scene);
		primaryStage.show();/* show the new screen */
	}
	
	/**
	 * This method sets the correct values of the businessCustomer in portal.
	 */
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		businessCustomerName.setText(connectedUser.getUserFirstName());
		companyName.setText(((BusinessCustomer)connectedUser).getcompanyOfBusinessCustomer().getCompanyName());
		statusText.setText(connectedUser.getStatusInSystem().toString());
		if(connectedUser.getStatusInSystem().equals(ConfirmationStatus.FROZEN)) {
			btnStartOrder.setDisable(true);
		}
		
	}
}
