package controllers_gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import communication.Answer;
import communication.Message;
import communication.Task;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;
import users.User;
import javafx.scene.control.ComboBox;

public class UserPortalOfBusinessCustomerController extends AbstractBiteMeController {
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Label customerNameLabel;
	@FXML
	private Button btnHelp;
	@FXML
	private Button btnStartOrder;
	@FXML
	private Label companyNameLabel;
	@FXML
	private ComboBox homeBranchCombo;
	

	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
		Message message= new Message(Task.LOGOUT,Answer.WAIT_RESPONSE,connectedUser);
		sendToClient(message);
		connectedUser=null;
		System.exit(0);
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	/**
	 * 
	 * @param event
	 */
	public void getLogoutBtn(ActionEvent event) {
		Message message= new Message(Task.LOGOUT,Answer.WAIT_RESPONSE,connectedUser);
		sendToClient(message);
		connectedUser=null;
		setToLoginScreen(event);
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnStartOrder].onAction
	@FXML
	public void getStartOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#homeBranchCombo].onAction
	@FXML
	public void getHomeBranch(ActionEvent event) {
		// TODO Autogenerated
	}
	
	/**
	 * 
	 * @param event
	 */
	private void setToLoginScreen(ActionEvent event) {
		Platform.runLater(new Runnable() {
			@Override
			public void run() {
				FXMLLoader loader = new FXMLLoader();
				Pane root;
				try {
					Stage Stage = new Stage();
					Stage.setResizable(false);
					root = loader.load(getClass().getResource("/fxmls/LoginScreen.fxml").openStream());
					Scene scene = new Scene(root);
					Stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
						@Override
						public void handle(WindowEvent event) { 
							event.consume();
							Stage.close();
						}
					});
					Stage.setScene(scene);
					Stage.show();
				} catch (IOException e) {
					e.printStackTrace();
				}
				((Node) event.getSource()).getScene().getWindow().hide();
			}
		});
	}
}
