package controllers_gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class UserPortalOfSupplierController {
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Button btnManageOrders;
	@FXML
	private Button btnManageMenu;
	@FXML
	private Label nameLabel;
	@FXML
	private Button btnHelp;

	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnManageOrders].onAction
	@FXML
	public void getManageOrdersBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnManageMenu].onAction
	@FXML
	public void getManageMenuBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
}
