package controllers_gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class UserPortalOfCustomerController {
	@FXML
	private Button btnStartOrder;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnLogout;
	@FXML
	private Button btnHelp;
	@FXML
	private ComboBox homeBranchComboBox;

	// Event Listener on Button[#btnStartOrder].onAction
	@FXML
	public void getStartOrderBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void getExitBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogout].onAction
	@FXML
	public void getLogoutBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHelp].onAction
	@FXML
	public void getHelpBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#homeBranchComboBox].onAction
	@FXML
	public void getHomeBranchComboBox(ActionEvent event) {
		// TODO Autogenerated
	}
}
