package communication;

/**
 * @author Lior, Guzovsky.
 * @author Alexander, Martinov
 * Class description: 
 * 
 * This is an enum that
 * helps us to set the operation
 * needed to be done by the server and client.
 *
 * @version 15/12/2021
 */
public enum Task {
	
	CONFIRM_IP,
	
	LOGIN,
	CREATE_USER_PORTAL,
	PRINT_ERROR_TO_SCREEN,
	LOGOUT,
	SET_HOMESCREEN,
	REGISTER_PRIVATE_CUSTOMER,
	REGISTER_BUSINESS_CUSTOMER,
	REGISTER_SUPPLIER,
	DISPLAY_MESSAGE_TO_CLIENT,
	GET_COMPANIES_FROM_DB,
	DISPLAY_COMPANIES_INTO_COMBOBOX,
	GET_CUSTOMERS_FROM_DB,
	DISPLAY_CUSTOMERS_INTO_TABLE,
	UPDATE_CUSTOMER_STATUS,
	REMOVE_USER_FROM_DB,
	GET_RESTAURANTS_FOR_ORDER,
	GET_RESTAURANTS_FOR_SUPPLIER_REGISTRATION,
	GET_SUPPLIER_FOR_SUPPLIER_REGISTRATION,
	GET_ITEMS_FOR_ORDER_MENU, 
}
